language: c
sudo: required
dist: trusty

services:
  - docker

before_script:
  - docker build -t packagekit-debian -f tests/ci/Dockerfile-debian .
  - docker build -t packagekit-fedora -f tests/ci/Dockerfile-fedora .

script:
  - docker run -t -v `pwd`:/build packagekit-debian ./contrib/ci/build_and_test.sh
  - docker run -t -v `pwd`:/build packagekit-fedora ./contrib/ci/build_and_test.sh
